baseURL = 'https://www.schaefer-itsec.com/'
languageCode = 'en-us'

theme = 'barks'
sectionPagesMenu = "main"




[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20
[[menu.main]]
  name = 'CV'
  url = '/CV'
  weight = 30
[[menu.main]]
  name = 'Appointments'
  url = 'http://schaefer-itsec.com/appointment'
  weight = 40

[params.head]
    author = "Felix Schaefer"
    description = "This is the academic biographical website of F. Schaefer!"
    keywords = ["academic", "biographical", "cyber security", "computer science", "research"]

[params.navigation]
    show_navigation = true

[params.footer]
    show_footer = true

[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:felix@oje-oje.de"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/Shepherd-ITSec"
        weight = 2
    [params.social.linkedin]
        name = "LinkedIn"
        class = "fab fa-linkedin"
        url = "https://linkedin.com/in/felix-schäfer"
        weight = 2

[params.colors]
    theme_color = "#c8c3bc"
    background_color = "#181a1b"
    text_color = "#c8c3bc"
    link_color = "#df8868"